### ISSUE TITLE
Upload errors on v2.1

### ISSUE THREAD

**Issue by inyono** [hotsapi/Hotsapi.Uploader#72]
Since a couple of days ago, I get upload errors:
```
[2020-10-09 09:33:50.9872] WARN: Error uploading file 'C:\Users\jk\Documents\Heroes of the Storm\Accounts\103183398\2-Hero-1-7913541\Replays\Multiplayer\2020-10-06 21.28.58 Alterac Pass.StormReplay' System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hotsapi.Uploader.Common.Uploader.<Upload>d__8.MoveNext()
```
(2020-09-05 was the last successful upload of a replay, 2020-10-06 is the first failing).

**Comment by CorvusVeis** [comment]
I'm encountering the same issue. 249 failed uploads, 0 successful.

**Comment by poma** [comment]
please try again

**Comment by CorvusVeis** [comment]
It's working again; thank you!

**Comment by inyono** [comment]
Yep, thanks 👍

**Comment by CorvusVeis** [comment]
Same problem again. Uploader doesn't work.
